### ISSUE TITLE
CatalogMatch handling multiple matches

### ISSUE THREAD

**Issue by wombaugh** [AmpelProject/Ampel-ZTF#69]
Make sure that CatalogMatch nicely handles cases where multiple matches are found within search radius.  Possible alternatives include returning all matches (in some way that is understood by downstream units), returning the closest in arcsec and returning the closest in physical distance. A prototype exists in CatalogMatchLocal (v7)

Filtering based on additional properties could be handled.

**Comment by jvansanten** [comment]
Addressed (I think) in 1ed3984a667872accafd0e53105606cbc753822c.
